[package]
name = "highs-sys"
version = "0.1.0"
authors = ["Ophir LOJKINE"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]

[build-dependencies]
bindgen = "0.57"
cmake = "0.1"