name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.config.os }} # we run many different builds
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    steps:
    - name: Set LIBCLANG_PATH
      run: echo "LIBCLANG_PATH=C:\msys64\mingw64\bin" >> $env:GITHUB_ENV
      if: matrix.config.os == 'windows-latest'
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install dependencies
      run: ./install-dependencies.sh
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
